## Install and set up PHP 7##

#fyi http://qiita.com/yudsuzuk/items/94fdc3dff58d37a9806f

- name: install dependency
  yum: name={{item}} enablerepo=epel,remi,remi-php70
  with_items:
    - php70 
    - php70-php-mcrypt 
    - php70-php-mbstring 
    - php70-php-fpm 
    - php70-php-gd 
    - php70-php-pecl-xdebug 
    - php70-php-pecl-redis 
    - php70-php-pecl-imagick-devel 
    - php70-php-pecl-imagick 
    - php70-php-mysqlnd 
    - php70-php-intl 
    - php70-php-bcmath 
    - php70-php-pecl-zip 
    - php70-php-xmlrpc 
    - php70-php-xml  
    - php70-php-pecl-http 
    - php70-php-pecl-http-devel 
    - php70-php-opcache
  register: install_dependency
- debug: var=install_dependency
  
- name: path settings
  shell: |
      cat /opt/remi/php70/enable
      export PATH=/opt/remi/php70/root/usr/bin:/opt/remi/php70/root/usr/sbin${PATH:+:${PATH}}
      export LD_LIBRARY_PATH=/opt/remi/php70/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      export MANPATH=/opt/remi/php70/root/usr/share/man:${MANPATH}
      source ~/.bashrc
      
- name: php-fpm settings
  replace: >
    dest=/etc/opt/remi/php70/php-fpm.d/www.conf
    regexp="group = apache"
    replace="group = nginx"
  replace: >
    dest=/etc/opt/remi/php70/php-fpm.d/www.conf
    regexp="user = apache"
    replace="user = nginx"
  replace: >
    dest=/etc/opt/remi/php70/php-fpm.d/www.conf
    regexp="listen = 127.0.0.1:9000"
    replace="listen = /var/run/php-fpm.sock
             listen.owner = nginx
             listen.group = nginx
             listen.mode = 0666"
             
- name: register php-fpm to service
  shell: cp -a /vagrant/config/php/php-fpm.txt /etc/systemd/system/php-fpm.service
             
- name: start php-fpm
  service: name=php-fpm state=started enabled=yes